### ISSUE TITLE
Wrong duration when using encode

### ISSUE THREAD

**Issue by akippnn** [familyfriendlymikey/mpv-cut#10]
Here's the MediaInfo for both files. Left is encode and right is copy.
![image](https://user-images.githubusercontent.com/80670461/216572229-ac45af51-fcbd-49e5-9ad3-f82f7f31046d.png)

Both files are cut at the exact frame. The issue is that the metadata for the encode is `13:33` even though MediaInfo suggests that the video should only be 48 seconds long. This error is not present for the copy file, where all duration fields have marginal error.

**Comment by familyfriendlymikey** [comment]
Does the name of the encode cut file show the correct time? If so then it seems like that'd be an issue with ffmpeg, the script just spawns this command:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/15002903/216666177-d5de9cd8-1cf0-4768-a29e-486e131f6f5d.png">

**Comment by akippnn** [comment]
Seems like it, both encode and copy files do end with `_FROM_00-10-06.523_TO_00-10-54.613`.

**Comment by familyfriendlymikey** [comment]
Hmm, maybe it's some ffmpeg nonsense then. I'll probably be making changes to the script so we'll see if those happen to address this.

**Comment by familyfriendlymikey** [comment]
I moved `-ss` and `-t` after `-i` in the latest release, this is likely fixed.

**Comment by akippnn** [comment]
Yup, I confirm it's fixed
![image](https://user-images.githubusercontent.com/80670461/216879105-cf3eb2c5-8cae-4d73-9fd9-a30e98bbe354.png)
