### ISSUE TITLE
Would it be possible to place the cut on another directory and not where the original one is?

### ISSUE THREAD

**Issue by Estebiu** [familyfriendlymikey/mpv-cut#12]
Let me explain: I have the majority of my shows on a samba share where I can't write and I'd like to be able to tell this script that when I make a cut on a file in a certain folder (where the samba share is) I want it to put in another directory (like ~/Videos/Cuts or something), but when I do a cut on a file that isn't in that location it just places it normally.

Would that be possible to implement?

**Comment by familyfriendlymikey** [comment]
One of the main design choices I made was to expose data to custom actions that you can add to in the config file. Here's the code for the `copy` action:

```lua
ACTIONS.COPY = function(d)
	local args = {
		"ffmpeg",
		"-nostdin", "-y",
		"-loglevel", "error",
		"-ss", d.start_time,
		"-t", d.duration,
		"-i", d.inpath,
		"-pix_fmt", "yuv420p",
		"-c", "copy",
		"-map", "0",
		"-avoid_negative_ts", "make_zero",
		utils.join_path(d.indir, "COPY_" .. d.channel .. "_" .. d.infile_noext .. "_FROM_" .. d.start_time_hms .. "_TO_" .. d.end_time_hms .. d.ext)
	}
	mp.command_native_async({
		name = "subprocess",
		args = args,
		playback_only = false,
	}, function() print("Done") end)
end
```

You can redefine this in your config file but save to a different directory like this:

```lua
utils.join_path(mp.command_native({"expand-path", "~/Videos/Cuts"}), "COPY_" .. d.channel .. "_" .. d.infile_noext .. "_FROM_" .. d.start_time_hms .. "_TO_" .. d.end_time_hms .. d.ext)
```

I forget if `expand-path` will properly expand `~/Videos/Cuts`, but if not you can look at the mpv docs.

**Comment by Estebiu** [comment]
Thanks a lot.
I finally can stop using OBS..

**Comment by Dunxter** [comment]
Hi! I've replicated this on my main.lua file but the file doesn't seem to be saved anywhere (and the Videos/Cuts/ directory isn't properly created in the opened file directory). Any advice is appreciated!
