### ISSUE TITLE
"Error reading cut list" when invoking MAKE_CUTS

### ISSUE THREAD

**Issue by novoid** [familyfriendlymikey/mpv-cut#13]
Hi,

I've just found your script which perfectly solves my use-case of splitting a video into (potential multiple) smaller ones. Unfortunately, my initial test ended in an error.

# Environment

Debian bookworm. mpv 0.35.1. FFmpeg version: 5.1.3-1.
I've set up your tool using the git command from the README.

# How to reproduce the error

1. `mpv video.mp4`
2. marking multiple positions using `i`
3. pressing `0` to start the cutting process(es) -> "Error reading cut list" is shown in the mpv overlay as well as on stdout

Since I freshly installed the script and I don't have other mpv scripts set up (yet), I assume this is a bug and not an error on my side.

Do you have any suggestion for me? Should I check something for analyzing the situation?

# Console output

```
user@host ~2cut % [mpv_cut] MPV-CUT LOADED. 
 (+) Video --vid=1 (*) (h264 720x576 25.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
[mpv_cut] ["infile_noext"] = video
[mpv_cut] ["inpath"] = video.mp4
[mpv_cut] ["ext"] = .mp4
[mpv_cut] ["indir"] = .
[mpv_cut] ["channel"] = 1
[mpv_cut] ["infile"] = video.mp4
[mpv_cut]  
AO: [pipewire] 48000Hz stereo 2ch floatp
VO: [gpu] 720x576 yuv420p
[mpv_cut] ["infile_noext"] = video
[mpv_cut] ["inpath"] = video.mp4
[mpv_cut] ["ext"] = .mp4
[mpv_cut] ["indir"] = .
[mpv_cut] ["channel"] = 1
[mpv_cut] ["infile"] = video.mp4
[mpv_cut]  
[mpv_cut] ["infile_noext"] = video
[mpv_cut] ["inpath"] = video.mp4
[mpv_cut] ["ext"] = .mp4
[mpv_cut] ["indir"] = .
[mpv_cut] ["channel"] = 1
[mpv_cut] ["infile"] = video.mp4
[mpv_cut]  
[mpv_cut] Δ 6, 1 
[mpv_cut] ["infile_noext"] = video
[mpv_cut] ["inpath"] = video.mp4
[mpv_cut] ["ext"] = .mp4
[mpv_cut] ["indir"] = .
[mpv_cut] ["channel"] = 1
[mpv_cut] ["infile"] = video.mp4
[mpv_cut]  
[mpv_cut] ["infile_noext"] = video
[mpv_cut] ["inpath"] = video.mp4
[mpv_cut] ["ext"] = .mp4
[mpv_cut] ["indir"] = .
[mpv_cut] ["channel"] = 1
[mpv_cut] ["infile"] = video.mp4
[mpv_cut]  
[mpv_cut] Δ 6, 1 
[mpv_cut] ["infile_noext"] = video
[mpv_cut] ["inpath"] = video.mp4
[mpv_cut] ["ext"] = .mp4
[mpv_cut] ["indir"] = .
[mpv_cut] ["channel"] = 1
[mpv_cut] ["infile"] = video.mp4
[mpv_cut]  
[mpv_cut] ["infile_noext"] = video
[mpv_cut] ["inpath"] = video.mp4
[mpv_cut] ["ext"] = .mp4
[mpv_cut] ["indir"] = .
[mpv_cut] ["channel"] = 1
[mpv_cut] ["infile"] = video.mp4
[mpv_cut]  
[mpv_cut] Δ 7, 1 
[mpv_cut] MAKING CUTS 
[mpv_cut] Error reading cut list 

Exiting... (Quit)

[1]  + 3569179 done       mpv video.mp4
user@host ~2cut % cat 1_video.mp4.book 
22.88
75.72
234.04
user@host ~2cut % 
```

**Comment by novoid** [comment]
Maybe you'd like to provide an example book file in the README so that people get an impression how it is supposed to look like. Maybe I do have a different locale/encoding and therefore the assumed format is different from you?

**Comment by familyfriendlymikey** [comment]
Bookmarks aren't for cuts, what you're looking for is is the LIST action that you can switch to with the "a" hotkey, and then choose a beginning and ending with the "c" hotkey. Then you can make the cuts.

**Comment by novoid** [comment]
Oh, so I completely misunderstood the README then?

I thought this script lets me (somehow) mark multiple timestamps and after invoking a shortcut, it splits up the original video into slices that have been marked. According your comment, I guess that is is not a functionality the script is able to provide? Instead, it is only able to cut between exactly two marked positions (and not multiple). Correct?

**Comment by familyfriendlymikey** [comment]
With the LIST action you mark the beginning and end of each slice, which creates a .list file. You can open it and see the format. Once you're done choosing all the slices you can make all the cuts with "0". It sounds like that's what you want?

You can also do this one by one without creating a .list file. You can just use the COPY or ENCODE actions to immediately create a slice.

It doesn't concatenate the video slices into one video but you can do that with ffmpeg.

**Comment by familyfriendlymikey** [comment]
At the end of the readme I explain how to concatenate the videos. I was thinking of including a script to concatenate but it's easy enough with bash as I show in the readme.

**Comment by novoid** [comment]
Ah, now I understand.

`a` toggles between COPY, ENCODE, LIST.

COPY and ENCODE do create slices between two `c` right away, no "need" to press `0` at all, no external file needs to get generated.

LIST acts just like COPY (only?) but doesn't create slices when the second `c` is pressed but instead, generates a list file with all the pairs of markers created by `c`. When I'm done marking all the slices, I may press `0` in order to start the generating of the slices. The list file is persisted in the file system and needs to be removed manually.

Is this correct?

If you want, I might submit a pull request for an improved README from my perspective which tries to prevent my misunderstanding.

**Comment by familyfriendlymikey** [comment]
Correct. The LIST action is for backup purposes. I prefer to use it instead of the others if I'm marking funny moments in a show for example.

You can configure which action is used when you press 0 by setting the MAKE_CUT variable to an action. By default it's set to ACTIONS.COPY.

And the actions themselves are very easily extensible so you can create your own or change an existing one to your liking, if you want to change the CRF or preset for the ENCODE action for example.

You can also change the order of the actions. I think this stuff is in the readme.

As far as a PR, I'm definitely open to it but I'd have to agree that it's clearer :)

**Comment by novoid** [comment]
Perfect.

Of course, my PR would be just a suggestion. It's your project and you don't have to use anything I'm writing. Sometimes, it helps getting a second opinion on documentation IMHO.

I think I fully understood the basic principle including the ACTIONS.COPY switch you've been mentioning.

One off-topic question: I noticed that some cuts are not that exactly in the cut result file. Does this relate to specific frames where cuts are able to be made? Is there a method to specifically jump to those frames? I think I've read somewhere that Shift-left/right ought to jump those frames that might be used for cutting. But I could not confirm that in my tests so far as cut videos still aren't exactly following my positions. Maybe you've got some advice for that. I'm running mpv as is with only adaptions related to the position of the OSD which should not interfere with the frame/cut issue at all.

Thanks for your support! Greetings from Graz/Austria.

**Comment by familyfriendlymikey** [comment]
That's because you're using the COPY action which only cuts on keyframes. The position of the keyframes depends on how the video was encoded. If you want to jump to keyframes, with mpv you can just set a hotkey to seek .0001 seconds or something, and this will go to the nearest keyframe (as long as you don't set the hotkey with EXACT or whatever it is).

If you want exact cuts you have to use ENCODE.

Happy to help, greetings from nowhere in particular but right now Spain :)
