### ISSUE TITLE
Extra duration when using ENCODE

### ISSUE THREAD

**Issue by githubchan0** [familyfriendlymikey/mpv-cut#17]
I only cutted from `00:05:06.473` to `00:05:06.473` but video properties says 00:05:12
Here is the video file
![2023-07-20 09_58_53](https://github.com/familyfriendlymikey/mpv-cut/assets/127070736/ce7cb696-c60b-41f8-b587-948ee6042d82)

Here is the timestamp, video ends/stop at `00:00:05`
![2023-07-20 10_01_06](https://github.com/familyfriendlymikey/mpv-cut/assets/127070736/ca19c296-1d9d-44ca-a8b1-67861781bd47)

**Comment by novoid** [comment]
I guess that's because when cutting without re-encoding, mpv-cut needs to go from one full frame to the next full frame. This adds some time to your original selection. At least this is what I've learned from the README.
