### ISSUE TITLE
No cut files are created

### ISSUE THREAD

**Issue by goto-engineering** [familyfriendlymikey/mpv-cut#2]
I'm using Linux. When I try cutting using either `c` or the cut list and `0`, no cut files appear. I tried toggling to global directory mode and they don't show up there, either.

I don't see any errors at all in the mpv logs, it just says "Making cuts" and then "Done."

I tried following the code, I suppose it's intended to call that make_cuts.imba file? I don't know if that ever happens, or if it fails in any way.

Any clue what I could try to debug?

**Comment by familyfriendlymikey** [comment]
Ah, I just converted the make_cuts script to another language which needs to be compiled to JS. I intended to package a release but put it off because I didn't know people would be interested in this project!

I can fix it when I get home, but if you want to make it work right now, you'd just run the build script. Assuming you have npx:
```
npx imba run build.imba
```

**Comment by familyfriendlymikey** [comment]
I made a release branch, you can download it by doing:
```
git clone -b release --single-branch "https://github.com/familyfriendlymikey/mpv-cut.git" ~/.config/mpv/scripts/mpv-cut
```
That should work as long as you have ffmpeg and node. Let me know if you have any issues.

**Comment by goto-engineering** [comment]
I tried both suggestions, still no cut videos showing up. I do have both
ffmpeg and node.

**Comment by familyfriendlymikey** [comment]
Hmm, I just made a fresh install of Manjaro, and ran
```
pamac install mpv yt-dlp nodejs
git clone -b release --single-branch "https://github.com/familyfriendlymikey/mpv-cut.git" ~/.config/mpv/scripts/mpv-cut
```
downloaded a video, and it worked out of the box.

You mentioned you made a cut list, try piping the contents to make_cuts and see if that produces any errors:
```
cat some_video.mp4.list | node ~/.config/mpv/scripts/mpv-cut/make_cuts
```

**Comment by goto-engineering** [comment]
Ah, that works. And since I see the same blue output in mpv output I
checked my global (Desktop) folder and it seems that it defaults to
global desktop output, all the videos are there.

I think it has been working since you uploaded the release version, I
just hadn't checked my global folder.

Thanks!

**Comment by familyfriendlymikey** [comment]
Oh, nice!

I put global on by default because I figured that's what most people would want, but if it's confusing maybe I'll make it default to local.
