### ISSUE TITLE
Is there way to choose audio track to cut from

### ISSUE THREAD

**Issue by bbrother92** [familyfriendlymikey/mpv-cut#22]
Script only cuts default audio

**Comment by familyfriendlymikey** [comment]
You can add an action to do that in your config file. Base it off of the existing ENCODE action and add the necessary ffmpeg flags.

**Comment by bbrother92** [comment]
Sir, what is ENCODE action?

**Comment by familyfriendlymikey** [comment]
https://github.com/familyfriendlymikey/mpv-cut?tab=readme-ov-file#custom-actions
