### ISSUE TITLE
Cant cut 10bit 4:2:2

### ISSUE THREAD

**Issue by Touning** [familyfriendlymikey/mpv-cut#26]
I think it is normal that i cant cut 4:2:2 10 bit from my gh5 but if someone could help me to do it with mpv-cut it would be incredible. Thanks !

**Comment by familyfriendlymikey** [comment]
Can you send a tiny sample video

**Comment by Touning** [comment]
Thanks for your fast answer, Here is a small video in the same codec. Greets
https://we.tl/t-qvN0EwL6Ps

**Comment by familyfriendlymikey** [comment]
So this is an issue with ffmpeg, I don't know why it fails to copy the stream to the mov container, but mkv works. So if you don't mind outputting mkv, then it'll work file. You'd just add this to your `config.lua` file:

```lua
ACTIONS.COPY = function(d)
	local args = {
		"ffmpeg",
		"-nostdin", "-y",
		"-loglevel", "error",
		"-ss", d.start_time,
		"-t", d.duration,
		"-i", d.inpath,
		"-c", "copy",
		"-map", "0",
		"-dn",
		"-avoid_negative_ts", "make_zero",
		utils.join_path(d.indir, "COPY_" .. d.channel .. "_" .. d.infile_noext .. "_FROM_" .. d.start_time_hms .. "_TO_" .. d.end_time_hms .. '.mkv')
	}
	mp.command_native_async({
		name = "subprocess",
		args = args,
		playback_only = false,
	}, function() print("Done") end)
end
```

If you don't want mkv output, you'll have to research why ffmpeg is failing with your footage. You could research some combination of `ffmpeg blank output copy stream g5 10 bit hdr 4:2:2` and try to find an ffmpeg command that will work. Then if you do find a solution, you'd modify this copy action with the revised command.

**Comment by familyfriendlymikey** [comment]
For example if you do `ffmpeg -i video.MOV -c copy out.MOV`, the result is still black.

It could also be something like our ffmpeg version. But I'll let you test all that :P

**Comment by Touning** [comment]
Thank you very much for your help ! I don't know the mkv but if it doesnt change the quality of the video it could be great ! :D I'm gonna check as well if i can solve this thru ffmpeg. I will post here if i find something. Have a great day !

**Comment by familyfriendlymikey** [comment]
mkv is just a different container, the cut will still be lossless. So it sounds like you should just add the code I sent you to your config.

You're welcome! Have a nice day :)
