### ISSUE TITLE
fellas, noob here. cut-video.lua is not working.

### ISSUE THREAD

**Issue by Nature0855** [familyfriendlymikey/mpv-cut#27]
ok idk why it is not working. In fact I also bricked by mpv a little. Let me know what I need to run to let yall know what the problem is

[debug] Command-line config: ['-vU', 'https://youtu.be/3hWpkXXXJhI']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-28-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5, websockets-9.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2024.04.09/SHA2-256SUMS
Current version: stable@2023.12.30 from yt-dlp/yt-dlp
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
Current Build Hash: 1965bf8dcf181a8e6adb99c0ec4cdaaae5e2d01ba1f5198f68535305d5ae94b2
Updating to stable@2024.04.09 from yt-dlp/yt-dlp ...
ERROR: Unable to write to /usr/local/bin/yt-dlp; try running as administrator
[youtube] Extracting URL: https://youtu.be/3hWpkXXXJhI
[youtube] 3hWpkXXXJhI: Downloading webpage
[youtube] 3hWpkXXXJhI: Downloading ios player API JSON
[youtube] 3hWpkXXXJhI: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] 3hWpkXXXJhI: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] 3hWpkXXXJhI: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] 3hWpkXXXJhI: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Loading youtube-nsig.8fc6998a from cache
[debug] [youtube] Decrypted nsig aETKNObiQpZpvJPi => IXAH77Bj2c9JGg
[debug] Loading youtube-nsig.8fc6998a from cache
[debug] [youtube] Decrypted nsig S21kgYuqxUppFSFH => jW-RaZS31CRA6A
[youtube] 3hWpkXXXJhI: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 3hWpkXXXJhI: Downloading 1 format(s): 605+251
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1714636777/ei/ifMyZs-1MtmEkucP4Jmk6AY/ip/24.169.6.163/id/de15a99175d72612/itag/605/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D622880%3Bdur%3D25.125%3Bgir%3Dyes%3Bitag%3D243%3Blmt%3D1674533834671149/rqh/1/hls_chunk_host/rr1---sn-ab5sznzl.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/Qq/mm/31,26/mn/sn-ab5sznzl,sn-vgqsknek/ms/au,onr/mv/m/mvi/1/pl/17/initcwndbps/1351250/vprv/1/playlist_type/DVR/dover/13/txp/6216224/mt/1714614780/fvip/2/short_key/1/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,vprv,playlist_type/sig/AJfQdSswRgIhANFck6XNYAtPJVEuPgagFlr4wa_I-PlFBfPi25Xw0I5zAiEAva5AIvPLHwgXkgsX8qrntqWZo7hTRxmnx2IlOSjV77s%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AHWaYeowRgIhAJdZoc-20q-nDayOWQ_Da6rgDIi2dVtCJlO_3O2oKi4OAiEAtRi_TbtDVZtdllqUcRg9HLvD4hYlPMQdkw7HnJtUg4M%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 5
[download] Destination: How They Rob Men in Chicago - 1900 - Wallace McCutcheon COLORIZED [3hWpkXXXJhI].f605.mp4
[download] 100% of  612.99KiB in 00:00:01 at 512.13KiB/s
[debug] Invoking http downloader on "https://rr1---sn-ab5sznzl.googlevideo.com/videoplayback?expire=1714636777&ei=ifMyZsm0C_mSkucP_5G3sAY&ip=24.169.6.163&id=o-ABskzxxusgja9b9lm5yixcbxoI_rWvd0mGc-umgAKQTd&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=Qq&mm=31%2C26&mn=sn-ab5sznzl%2Csn-vgqsrnek&ms=au%2Conr&mv=m&mvi=1&pl=17&initcwndbps=1161250&bui=AWRWj2SQnR0kb506Ckogm5mzOS3ZkZPU_15LJvZwR28Gv4TDez0Qh_CYN7zxM_FTVecq1icV8Avm1w_c&spc=UWF9f9ET8R6GHT45IYT08TmdIo9ntMq_DQD74_SLUzKBvUFr6da1RJ5xHiFM&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=L3a39hfZ6tHTeY_hMvc1PhQQ&gir=yes&clen=11650&dur=25.121&lmt=1625838689573507&mt=1714615012&fvip=1&keepalive=yes&c=WEB&sefc=1&txp=6211224&n=jW-RaZS31CRA6A&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhALqQIg-vhd912NaOk__UEhCg5ii4Oa17OdeEX27e77UmAiEAu8GNVAt6kooDb_SilU_ouKm6p8sm5EaW86TPL7uW-_E%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIgbU9YlUlol51W0dYLQn4YErkJ6JOIhFoIqp7UpEGQUcsCIQCImxG_ugsRtxxidHGMRKOeGsfFEBe9hSSt1D6u28g-dA%3D%3D"
[download] Destination: How They Rob Men in Chicago - 1900 - Wallace McCutcheon COLORIZED [3hWpkXXXJhI].f251.webm
[download] 100% of   11.38KiB in 00:00:00 at 81.89KiB/s
[Merger] Merging formats into "How They Rob Men in Chicago - 1900 - Wallace McCutcheon COLORIZED [3hWpkXXXJhI].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:How They Rob Men in Chicago - 1900 - Wallace McCutcheon COLORIZED [3hWpkXXXJhI].f605.mp4' -i 'file:How They Rob Men in Chicago - 1900 - Wallace McCutcheon COLORIZED [3hWpkXXXJhI].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:How They Rob Men in Chicago - 1900 - Wallace McCutcheon COLORIZED [3hWpkXXXJhI].temp.webm'
Deleting original file How They Rob Men in Chicago - 1900 - Wallace McCutcheon COLORIZED [3hWpkXXXJhI].f251.webm (pass -k to keep)
Deleting original file How They Rob Men in Chicago - 1900 - Wallace McCutcheon COLORIZED [3hWpkXXXJhI].f605.mp4 (pass -k to keep)

**Comment by Nature0855** [comment]
[cut_video] ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
[cut_video]   built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
[cut_video]   configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
[cut_video]   WARNING: library configuration mismatch
[cut_video]   avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc --enable-libsmbclient
[cut_video]   libavutil      56. 70.100 / 56. 70.100
[cut_video]   libavcodec     58.134.100 / 58.134.100
[cut_video]   libavformat    58. 76.100 / 58. 76.100
[cut_video]   libavdevice    58. 13.100 / 58. 13.100
[cut_video]   libavfilter     7.110.100 /  7.110.100
[cut_video]   libswscale      5.  9.100 /  5.  9.100
[cut_video]   libswresample   3.  9.100 /  3.  9.100
[cut_video]   libpostproc    55.  9.100 / 55.  9.100
AV: 00:00:12 / 00:00:25 (48%) A-V:  0.000 Cache: 12s/770KB
[cut_video] https://youtu.be/3hWpkXXXJhI: Invalid data found when processing input
[cut_video] result:

**Comment by familyfriendlymikey** [comment]
There is nothing named cut_video in this repository, perhaps you meant to comment on a different plugin?
