### ISSUE TITLE
It didnt save the clip after it said "done"

### ISSUE THREAD

**Issue by Nature0855** [familyfriendlymikey/mpv-cut#28]
It didn't save the the clip in my directory after saying done. Am I missing something? 

[statusline] AV: 00:00:21 / 00:22:01 (2%) A-V:  0.000 Cache: 25s/1MB
[mpv_cut] COPY 
[mpv_cut] ["indir"] = https://youtu.be/
[mpv_cut] ["end_time"] = 21.988633333333
[mpv_cut] ["start_time_hms"] = 00-00-07-841
[mpv_cut] ["inpath"] = https://youtu.be/B-yqjttO1_Q
[mpv_cut] ["end_time_hms"] = 00-00-21-988
[mpv_cut] ["duration"] = 14.147466666667
[mpv_cut] ["start_time"] = 7.8411666666667
[mpv_cut] ["channel"] = 1
[mpv_cut] ["infile"] = B-yqjttO1_Q
[mpv_cut] ["ext"] = .mp4
[mpv_cut] ["duration_hms"] = 00-00-14-147
[mpv_cut] ["infile_noext"] = B-yqjttO1_Q
[mpv_cut]  
[mpv_cut] Done 
[statusline] AV: 00:00:21 / 00:22:01 (2%) A-V:  0.000 Cache: 25s/1MB
[osd/libass] libass API version: 0x1502000
[osd/libass] libass source: tarball: 0.15.2
[osd/libass] Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 2.7.4 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf, 0, DejaVuSans
[vo/gpu] Reallocating OSD texture to 256x256.

**Comment by Nature0855** [comment]
sorry I clicked enter when I just started typing the issue

**Comment by Nature0855** [comment]
nvm

**Comment by familyfriendlymikey** [comment]
Sorry, doesn't work with youtube links. Download your video with yt-dlp first.
