### ISSUE TITLE
macOS installation advice

### ISSUE THREAD

**Issue by stttkm** [familyfriendlymikey/mpv-cut#29]
Hi!
I tried to install the plugin using the instruction given in this repo. Unfortunately, it didn't work. After some tinkering I managed to make it work. I had to give an explicit path to ffmpeg in ACTIONS instead of giving just "ffmpeg". I obtained the explicit path by running "which ffmpeg" in bash.

```lua
ffmpeg_path = "/opt/homebrew/bin/ffmpeg"

ACTIONS.COPY = function(d)
	local args = {
		ffmpeg_path,
		"-nostdin", "-y",
		"-loglevel", "info",
		"-ss", d.start_time,
		"-t", d.duration,
		"-i", d.inpath,
		"-c", "copy",
		"-map", "0",
		"-dn",
		"-avoid_negative_ts", "make_zero",
		utils.join_path(d.indir, "COPY_" .. d.channel .. "_" .. d.infile_noext .. "_FROM_" .. d.start_time_hms .. "_TO_" .. d.end_time_hms .. d.ext)
	}
```

Idk what the cause of this issue is. Maybe my machine is just weird. I think we should include a warning or a known issue in the installation instruction for macOS.

**Comment by familyfriendlymikey** [comment]
That is in the requirements section: https://github.com/familyfriendlymikey/mpv-cut?tab=readme-ov-file#requirements
