### ISSUE TITLE
Subtitle styling is removed.

### ISSUE THREAD

**Issue by hxpelessrxmantic** [familyfriendlymikey/mpv-cut#6]
On choosing any of the cutting modes, the subtitles in a video lose all styling and become basic subtitles. Is there a way to retain the styling while making the cut?

**Comment by familyfriendlymikey** [comment]
With the encode cut, softsubs shouldn't be in the resulting video at all. With the copy cut, in the videos I have, I don't notice any change in the subtitle styling. But maybe all the videos I have just use the default styling already?

Either way, it would come down to ffmpeg. It just copies the input stream though so I'm not sure why it would change the subtitle styling.

**Comment by hxpelessrxmantic** [comment]
Mostly anime has a lot of styling so a lot of it is loss although it retains some basic styling like colours and such however the fonts are not the same. Could be something wrong with "ASS Style Override" of mpv. Can you check it out and try to maybe fix it? If not then you can close this issue.

**Comment by familyfriendlymikey** [comment]
If you find an ffmpeg flag or something that fixes the issue, I'm happy to try it out and make it a part of the script. Unfortunately I don't have time to look into it myself.

**Comment by familyfriendlymikey** [comment]
I pushed a new release which might solve this problem as well. You can update with `git pull` and try it out if you want.

**Comment by hxpelessrxmantic** [comment]
Just tested it out and it now retains tyling for stuff like kfx and sfx. Also, it outputs all the subtitles in the original file unlike just one like the previous version. Also, fonts and colors have been retained. Thanks for fixing.

**Comment by familyfriendlymikey** [comment]
Awesome! Thank you for reporting back :)
