### ISSUE TITLE
Pressing 'c' doesn't work

### ISSUE THREAD

**Issue by akippnn** [familyfriendlymikey/mpv-cut#8]
mpv_cut is installed correctly. stdout shows
`[mpv_cut] MPV-CUT LOADED`
Pressing `a`, `g`, and `l` does work and does toggle between modes. Pressing `0` however, gives the error "Failed to load cut list". Pressing `c` does nothing.

The script sometimes works when the -v option is specified, and it does make the cuts. But when it doesn't, no error shows up in the verbose output.

Winver is 21H2 (OS Build 19044.2486)

**Comment by familyfriendlymikey** [comment]
Thanks for reporting.

The cut list one might be a bug, I can look into it later.

Pressing `c` doesn't even show `COPY in <channel> from <time>` at the top left? Do you have something else overwriting the hotkey?

**Comment by akippnn** [comment]
It looks like a reboot fixed the issue. Although the cut list still gives the error `Failed to load cut list`. 

Yeah, pressing `c` didn't show `COPY in <channel> from <time>` but didn't do anything else. However, after the reboot, everything works perfectly.

If there's anything else I can do especially with the cut list, let me know.

**Comment by akippnn** [comment]
My bad, cut list does work as well. Seems like everything's good.

I've encountered an issue with the encoding mode though, but I'll open that in a new issue.
