### ISSUE TITLE
When I cut a video for lossless, it only gives me the 1st Audio channel and 1st Subtitle.

### ISSUE THREAD

**Issue by loser1994** [familyfriendlymikey/mpv-cut#9]
Decided to open another thread for this one. When you cut the video lossless it gives me only the 1st audio and subtitle. It supposed to bring every audio and subtitle when u cut a video. This is the error that shows on MPV

![2023-02-01 22_28_33- SCY  Psycho-Pass_ The Movie (BD 1080p Hi10 FLAC)  Dual-Audio  - mpv](https://user-images.githubusercontent.com/77483499/216442703-c94e4f3d-7d5a-4fbc-85e1-ab3a21e1b8dc.png)

It doesn't work no matter if the video is .MKV, .MP4 etc. I'm not entirely sure what is the issue

**Comment by familyfriendlymikey** [comment]
Pushed a new release, should solve the problem. To update just run `git pull`.
